export const catalogMock = [
  {
    id: 1,
    title: 'Традиции и элегантность',
    subtitle: 'В вашем интерьере',
    caption: 'Шкафы классические',
    img: 'http://placekitten.com/300/300',
    href: '/',
  },
  {
    id: 2,
    title: 'tilte',
    subtitle: 'subtitle',
    caption: 'caption',
    img: 'http://placekitten.com/300/300',
    href: '/',
  },
  {
    id: 3,
    title: 'tilte',
    subtitle: 'subtitle',
    caption: 'caption',
    img: 'http://placekitten.com/300/300',
    href: '/',
  },
  {
    id: 4,
    title: 'tilte',
    subtitle: 'subtitle',
    caption: 'caption',
    img: 'http://placekitten.com/300/300',
    href: '/',
  },
  {
    id: 5,
    title: 'tilte',
    subtitle: 'subtitle',
    caption: 'caption',
    img: 'http://placekitten.com/300/300',
    href: '/',
  },
  {
    id: 6,
    title: 'tilte',
    subtitle: 'subtitle',
    caption: 'caption',
    img: 'http://placekitten.com/300/300',
    href: '/',
  },
];
